chore: improve .gitignore and remove .DS_Store
MilanCommunity/Milan pull request #1010
Opened 2023-08-08 08:38 UTC by Anmol-Baranwal

### Related Issue 

Closes: #966

#### Changes made 👷🏻‍♂️

- Removed `.DS_Store`
- Updated `.gitignore` (I have avoided duplicate ones)

2023-08-09 07:21 UTC, tamalCodes requested changes
Please remove all declarations of files from `.gitignore` whose chances of getting used are none. Like yarn, next, grunt, istanbul and so on. We need not have our `.gitignore` so long and ignore all possible things. 

Please update accordingly.

2023-08-09 07:21 UTC, tamalCodes commented on .gitignore
> +package-lock.json
Please remove `./package-lock.json` and `package-lock.json` from here. They are files which needs to be in our repo for builds to kick-in.

2023-08-09 07:21 UTC, tamalCodes commented on .gitignore
> +
Please remove files related to nextjs, we are not using these files anyways.

2023-08-09 07:21 UTC, tamalCodes commented on .gitignore
> +
There is no need to add anything related to Typescript as of now. Please remove these.

2023-08-09 07:21 UTC, tamalCodes commented on .gitignore
> +
Please remove `REPL history` from here, we are anyways not using them.

2023-08-09 07:21 UTC, tamalCodes commented on .gitignore
> +
No need to add `yarn` files either, we are anyways not using them.

2023-08-09 07:21 UTC, tamalCodes commented on .gitignore
> +
Please remove everything related to env here, we have those in line number 26.

2023-08-13 11:53 UTC, Anmol-Baranwal commented
@tamalCodes 

I can still do this till 16th since I am very busy with Web3Conf, so I am not able to devote proper time.

2023-08-13 17:22 UTC, tamalCodes commented
So glad to hear that, I closed majority Issues because most of them were targeted at GSSOC with not much actual intrest in OSS. I'll re-open this up.

2023-08-17 05:31 UTC, Anmol-Baranwal commented
Done.

2023-08-20 09:22 UTC, merged

2023-08-20 17:50 UTC, Anmol-Baranwal commented
@tamalCodes 
Feel free to tag me, if there are any open issues, that you want me to take.