feat: enable direct access to signup/signin form from respective buttons and merged two types of authetication in one page
MilanCommunity/Milan pull request #1041
Opened 2023-08-17 07:57 UTC by VanshVg

### 🚧 Fixes Issue 

closes #1038 

### Changes made 👷🏻
Removed the modal which was being opened after clicking Signup/Signin button, Now it directly opens a Form.
Added dropdown menu in form which contains two options "Club" and "User" and will show respective fields according to the choice made.
Added a validation for password and confirm password meaning those two should be same otherwise it will show error Toast.

### Screenshots  📸
![image](https://github.com/MilanCommunity/Milan/assets/88078960/e9713395-c0b5-47d7-94bb-0448c030a03e)

![image](https://github.com/MilanCommunity/Milan/assets/88078960/0ce39cb4-98af-476e-8df1-f723c700cc5c)

![image](https://github.com/MilanCommunity/Milan/assets/88078960/b8661e76-130a-4696-99c0-cee8132ae64f)

### Note to Reviewers
Added two new files named "AuthLogin.jsx" and "AuthRegister.jsx" inside /src/pages/Auth.
Removed folders named club and user from /src/pages/Auth since it wasn't required anymore.

2023-08-17 16:58 UTC, tamalCodes requested changes

2023-08-17 16:58 UTC, tamalCodes commented on src/components/Banners/HomeBanner.jsx
Instead of adding functions to navigate to other pages here, we can do these inside of our custom [Button Component](https://github.com/MilanCommunity/Milan/blob/main/src/components/Button/GlobalButton/Button.jsx), write the functions there, and then based on the props that we pass the function can be called. 

Example, 

```jsx
<Button
    size="sm"
    variant="solid"
    action="login"
>
```

Based on what we pass to the action, run the function inside the Button component. Same goes for the Navbar too. This will avoid duplication and extra codes.

2023-08-17 16:58 UTC, tamalCodes commented on src/pages/Auth/AuthRegister.jsx
![image](https://github.com/MilanCommunity/Milan/assets/72851613/3c59891f-75da-42e0-a15f-1e63369a644e)

Loved the changes that were done, however, i think we can have some more changes. 

First of all change the user type on the UI, currently the User Type of `user` can confuse people.  
![image](https://github.com/MilanCommunity/Milan/assets/72851613/a33c3001-d198-4c0b-aee7-358e2bcadff5)


- For example, we can have a drop-down icon on the right side of the text for better UX.
- Please add full `Pincode / Zipcode` in the heading.
- Please make sure that the type of the pincode `type="text"`
- The `Club Name` input field should be full width.
- Please add the same placeholders as we had before, the placeholders can be dynamic with the help of conditional rendering `placeholder={userType==="individual" ? 'john@example.com' : 'peepal@farm.io"'} `

2023-08-18 08:01 UTC, VanshVg commented on src/components/Banners/HomeBanner.jsx
Yes, That would be better.
I'll make the changes.

2023-08-19 05:52 UTC, tamalCodes commented
Hi @VanshVg , i think you did the changes in the correct manner. Whenever you will push changes to the branch it will all show up here. Just 2 more things I would like to add.

- Instead of huge commit messages like `feat: merging the authentication pages of 2 different types of users` you can add short messages too like `fix: replaced placeholders with old one` and so on. The smaller it is the better it feels to read.
![image](https://github.com/MilanCommunity/Milan/assets/72851613/7045a52f-450f-44e4-914f-29ff459b6b3e)

Another thing is clicking on the `resolve conversation` button whenever you have done and committed those changes. It helps. As you can see `outdated` means, you have changed this file, so clicking on that resolve conversation button just makes things more professional.

2023-08-19 06:10 UTC, VanshVg commented
Okay, I'll keep these things in mind.
Thanx for the help.

2023-08-19 08:52 UTC, tamalCodes approved these changes
### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

2023-08-19 08:55 UTC, merged