fix: password validation
MilanCommunity/Milan pull request #1044
Opened 2023-08-18 12:23 UTC by pamechayash

closes #1043 

Steps that I have taken 
1. I made a new util named ProjectValidations.js, which contains all logic to validate passwords using regex.
2. then use this util in UserRegister and ClubRegister to validate the password before submitting to the backend

my changes will validate the password and check if the main password matches the confirm password.

2023-08-18 13:58 UTC, tamalCodes commented
Please change the branch to `beta` from `main`

2023-08-18 14:04 UTC, pamechayash commented
branch changed to beta

2023-08-19 09:03 UTC, tamalCodes requested changes

2023-08-19 09:03 UTC, tamalCodes commented on src/utils/PasswordValidation.js
> +    return { auth: false, message: "Password should not be less than 8" };
```suggestion
    return { auth: false, message: "Password should not be less than 8 characters" };
```

2023-08-19 09:03 UTC, tamalCodes commented on src/utils/PasswordValidation.js
> +      message: "Password should contains atleast one special characters",
```suggestion
      message: "Password should contain atleast one special character",
```

2023-08-19 09:04 UTC, tamalCodes commented
Also as said previously there are some minor conflicts as some files have been removed. 
Please take a look at #1041 to have a better understanding of the changes that were done/

2023-09-02 07:38 UTC, tamalCodes commented
### Let's catch up !
Hi @pamechayash , it has been a while since we last had a conversation so I wanted to know if you are still working on this. Please drop a reply shortly so that we know you are active, feel free to convey any problem you face in the comments, or mail me at tamalcodes@gmail.com. 

> [!WARNING]  
> The PRs are generally closed by 3 weeks if there has been no activity.

2023-09-07 04:09 UTC, closed without merging