fix: fixed functioning of contact us button in footer
MilanCommunity/Milan pull request #1140
Opened 2023-10-18 12:27 UTC by MahendraDani

closes #1131 
closes #1141

### 👷🏻 Changes made  

1. Fixed the modal component. Modal component can now have dynamic children as per the need.
2. On clicking the `contact us` button , a modal opens where user can report a problem. The Endpoint is `/user/report`.

### 📸 Screenshots 
 

https://github.com/MilanCommunity/Milan/assets/116940083/50bbb5e4-e922-4b57-9205-7ccee6eaf357

The above recording shows three things-
1. Proper functioning of `contact us` button and `modal` both.
2. Sucessfull API call to **report problem route.**
3. Proper functioning of database, where the report is stored as expected.

2023-10-22 07:01 UTC, tamalCodes requested changes

2023-10-22 07:01 UTC, tamalCodes commented on src/components/Modal/Modal.jsx
We are using two different fonts `Inter` for the headings and `Poppins` for the normal text and buttons.
Please make sure that the fonts are taken care of along with the color of the text in the modal.

2023-10-22 07:06 UTC, MahendraDani commented on src/components/Modal/Modal.jsx
Would you please tell me the text color hex codes ?

2023-10-22 07:08 UTC, tamalCodes commented on src/components/Modal/Modal.jsx
For the heading, it would be `#28183b`, and for the normal text we have it as `#000000`

2023-10-22 07:21 UTC, MahendraDani commented on src/components/Modal/Modal.jsx
Thanks, will make the necessary changes

2023-10-22 08:27 UTC, MahendraDani commented
## Applied changes
1. Added font-family *Inter* to headers and *Poppins* to normal text in modals.
2. Removed irrelevant text from console, fixes #1141 

## Before
![Screenshot (25)](https://github.com/MilanCommunity/Milan/assets/116940083/190e6ef5-479a-4be9-9aaf-079837141c38)

## After
![Screenshot (24)](https://github.com/MilanCommunity/Milan/assets/116940083/0606f0f6-24af-4e41-93c2-b1fb40b36059)

@tamalCodes If there are any other changes please let me know.

2023-10-22 08:29 UTC, MahendraDani commented on src/components/Modal/Modal.jsx
@tamalCodes Made changes and pushed in https://github.com/MilanCommunity/Milan/pull/1140/commits/e118422d6932bc8a399794f118937dddf7e921c4

2023-10-26 14:35 UTC, tamalCodes commented on src/components/Footer/Footer.css
> +  font-family: "Inter";
```suggestion
  font-family: "Inter",sans-serif;
```

2023-10-26 14:35 UTC, tamalCodes commented on src/components/Footer/Footer.css
> +  font-family: "Poppins";
```suggestion
  font-family: "Poppins"sans-serif;
```

2023-10-26 14:35 UTC, tamalCodes commented on src/components/Footer/Footer.css
> +  font-family: "Poppins";
```suggestion
  font-family: "Poppins"sans-serif;
```

2023-10-26 14:49 UTC, tamalCodes approved these changes
# Amazing work 🎉
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/MilanCommunity/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

2023-10-26 14:50 UTC, merged

2023-10-26 15:09 UTC, MahendraDani commented
@tamalCodes Thanks for merging this pull request.
If any issues need addressing I am up for grabs!